"use client"

import { useEffect, useRef, useState, type FormEvent } from "react"
import { Check, LoaderCircle, ShieldAlert } from "lucide-react"
import { useRouter } from "next/navigation"
import { gsap, reducedMotion } from "@/lib/motion"

async function request(url: string, method: string, body?: Record<string, unknown>) { const response = await fetch(url, { method, headers: { "content-type": "application/json" }, body: body ? JSON.stringify(body) : undefined }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error || "Unable to complete admin action."); return payload }
export function AdminReveal({ children, className = "" }: { children: React.ReactNode; className?: string }) { const ref = useRef<HTMLDivElement>(null); useEffect(() => { if (!ref.current || reducedMotion()) return; const context = gsap.context(() => gsap.fromTo(ref.current, { y: 10, opacity: 0 }, { y: 0, opacity: 1, duration: .4, ease: "power3.out" }), ref); return () => context.revert() }, []); return <div ref={ref} className={className}>{children}</div> }
export function AdminJobAction({ id, status }: { id: string; status: string | null }) { const [busy, setBusy] = useState(false); const router = useRouter(); const next = status === "Active" ? "Paused" : "Active"; async function act(value: string) { setBusy(true); try { await request(`/api/admin/jobs/${id}`, "PATCH", { status: value }); router.refresh() } finally { setBusy(false) } } return <div className="admin-row-actions"><button className="action-button action-ghost" type="button" disabled={busy} onClick={() => act(next)}>{busy ? "Saving..." : next === "Active" ? "Approve" : "Pause"}</button>{status !== "Archived" && <button className="action-button action-ghost" type="button" disabled={busy} onClick={() => act("Archived")}>Archive</button>}</div> }
export function AdminSuspendButton({ id, banned }: { id: string; banned: boolean | null }) { const [busy, setBusy] = useState(false); const router = useRouter(); async function toggle() { setBusy(true); try { await request(`/api/admin/users/${id}`, "PATCH", { banned: !banned }); router.refresh() } finally { setBusy(false) } } return <button className="admin-icon-action" type="button" disabled={busy} onClick={toggle} aria-label={banned ? "Reactivate user" : "Suspend user"}>{banned ? <Check size={16} aria-hidden="true" /> : <ShieldAlert size={16} aria-hidden="true" />}</button> }
export function AdminToggle({ url, active }: { url: string; active: boolean }) { const [enabled, setEnabled] = useState(active); const [busy, setBusy] = useState(false); const router = useRouter(); async function toggle() { setBusy(true); try { await request(url, "PATCH", { active: !enabled }); setEnabled(!enabled); router.refresh() } finally { setBusy(false) } } return <button className={`admin-status ${enabled ? "is-active" : "is-inactive"}`} type="button" disabled={busy} onClick={toggle}>{enabled ? "Active" : "Inactive"}</button> }
export function TaxonomyForm({ resource }: { resource: "categories" | "locations" }) { const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const router = useRouter(); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = event.currentTarget; const data = new FormData(form); try { await request(`/api/admin/${resource}`, "POST", Object.fromEntries(data.entries())); setMessage("Created."); form.reset(); router.refresh() } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to create record.") } finally { setBusy(false) } } return <form className="admin-inline-form" onSubmit={submit}><input className="input" name="name" placeholder={`New ${resource.slice(0, -1)} name`} required /><input className="input" name="slug" placeholder="slug" /><button className="action-button action-primary" type="submit" disabled={busy}>{busy ? <LoaderCircle className="spin" size={16} aria-hidden="true" /> : "Create"}</button>{message && <span role="status" className="admin-form-message">{message}</span>}</form> }
