export const locations = ["Victoria Island", "Ikorodu", "Oshodi-Isolo", "Badagry", "Ikeja", "Agege"]

export const demoJobs = [
  { id: "product-designer", title: "Product Designer", category: "Design & Creative", location: "Victoria Island", type: "Full-time", mode: "Hybrid", level: "Experienced", mark: "✳", color: "yellow", description: "Help turn complex ideas into thoughtful, useful digital experiences. This sample role demonstrates how design opportunities will appear on ADDOZ.", skills: ["Product thinking", "Figma", "Prototyping"] },
  { id: "frontend-developer", title: "Frontend Developer", category: "Development & IT", location: "Ikeja", type: "Full-time", mode: "Remote", level: "Experienced", mark: "</>", color: "blue", description: "Build accessible interfaces and collaborate with designers to bring digital products to life. This is an illustrative development role, not an active vacancy.", skills: ["React", "TypeScript", "Accessibility"] },
  { id: "marketing-specialist", title: "Digital Marketing Specialist", category: "Marketing & Sales", location: "Victoria Island", type: "Full-time", mode: "On-site", level: "Experienced", mark: "↗", color: "orange", description: "Connect thoughtful campaigns with the people they are made for. This sample role shows the structure of marketing opportunities on ADDOZ.", skills: ["Content strategy", "Analytics", "Communication"] },
  { id: "customer-success", title: "Customer Success Associate", category: "Customer Service", location: "Ikorodu", type: "Full-time", mode: "Hybrid", level: "Entry level", mark: "+", color: "yellow", description: "Help customers find answers and get more from the products they use. This illustrative role is included to demonstrate entry-level job discovery.", skills: ["Customer support", "Problem solving", "Communication"] },
  { id: "product-manager", title: "Product Manager", category: "Product Management", location: "Ikeja", type: "Contract", mode: "Remote", level: "Experienced", mark: "◎", color: "blue", description: "Bring teams together around a clear product direction. This is a sample contract role for exploring the job-discovery prototype.", skills: ["Product strategy", "Research", "Prioritisation"] },
  { id: "content-writer", title: "Content Writer", category: "Writing & Translation", location: "Agege", type: "Internship", mode: "Remote", level: "Entry level", mark: "Aa", color: "orange", description: "Make ideas clear through helpful, human writing. This illustrative internship demonstrates early-career opportunities, not a live opening.", skills: ["Writing", "Editing", "Research"] },
] as const

export type DemoJob = (typeof demoJobs)[number]
export const sourceSite = "https://addozconsultinglimited.com"
