import Link from "next/link"
import { headers } from "next/headers"
import { ArrowUpRight, BellRing, BriefcaseBusiness, FileText, Heart, Sparkles } from "lucide-react"
import { CandidateReveal, CandidateSaveButton } from "@/features/candidates/components/candidate-ui"
import { getCandidateOverview } from "@/features/candidates/queries"
import { formatFileSize } from "@/lib/format"

export default async function CandidateDashboardPage() {
  const data = await getCandidateOverview(await headers())
  const firstName = data.user.name.split(/\s+/)[0] || "there"
  return <CandidateReveal className="candidate-page">
    <header className="app-page-header candidate-hero">
      <div><p className="app-eyebrow">Candidate dashboard</p><h1>Good morning, {firstName}.</h1><p className="app-page-lead">A calmer place to keep your search moving, one useful next step at a time.</p></div>
      <div className="app-page-actions"><Link className="action-button action-primary" href="/jobs"><BriefcaseBusiness size={17} aria-hidden="true" />Browse jobs</Link><Link className="action-button action-ghost" href="/candidate/profile">Complete profile <ArrowUpRight size={16} aria-hidden="true" /></Link></div>
    </header>

    <section className="candidate-overview-grid" aria-label="Candidate overview">
      <article className="candidate-panel candidate-completion"><div className="panel-heading"><div><p className="app-eyebrow">Profile strength</p><h2>{data.completion}% complete</h2></div><span className="completion-ring" style={{ "--completion": `${data.completion}%` } as React.CSSProperties}>{data.completion}%</span></div><p>Add the details that help the right people understand your work.</p><div className="candidate-progress"><span style={{ width: `${data.completion}%` }} /></div><Link className="inline-link" href="/candidate/profile">Review your profile <ArrowUpRight size={15} aria-hidden="true" /></Link></article>
      <article className="candidate-panel candidate-resume-card"><div className="panel-heading"><div><p className="app-eyebrow">Resume status</p><h2>{data.resume ? "Ready to send" : "Add your resume"}</h2></div><FileText size={27} aria-hidden="true" /></div><p>{data.resume ? `${data.resume.fileName}${data.resume.fileSize ? ` · ${formatFileSize(data.resume.fileSize)}` : ""}` : "You need a CV on your profile to apply for jobs. Upload it once and it goes with every application."}</p><Link className="inline-link" href="/candidate/resume">{data.resume ? "Manage resume" : "Add resume"} <ArrowUpRight size={15} aria-hidden="true" /></Link></article>
    </section>

    <section className="candidate-dashboard-grid">
      <div className="candidate-panel"><div className="panel-heading"><div><p className="app-eyebrow">For your next move</p><h2>Recommended jobs</h2></div><Link className="text-link" href="/jobs">Browse all <ArrowUpRight size={15} aria-hidden="true" /></Link></div>{data.recommendations.length ? <ul className="candidate-job-list">{data.recommendations.map(item => <li key={item.id}><div className="candidate-job-main"><Link href={`/jobs/${item.slug}`}><strong>{item.title}</strong></Link><small>{item.companyName} · {item.locationName ?? "Flexible location"} · {item.categoryName ?? "Open role"}</small></div><CandidateSaveButton jobSlug={item.slug} title={item.title} /></li>)}</ul> : <div className="candidate-empty"><p>Recommendations will appear as new roles are posted.</p><Link className="inline-link" href="/jobs">Explore jobs</Link></div>}</div>
      <div className="candidate-panel"><div className="panel-heading"><div><p className="app-eyebrow">Keep an eye on</p><h2>Recent applications</h2></div><Link className="text-link" href="/candidate/applications">View all <ArrowUpRight size={15} aria-hidden="true" /></Link></div>{data.applications.length ? <ul className="candidate-job-list">{data.applications.slice(0, 3).map(item => <li key={item.id}><div className="candidate-job-main"><Link href={`/jobs/${item.slug}`}><strong>{item.title}</strong></Link><small>{item.companyName} · {item.stage ?? "Applied"}</small></div><time>{new Date(item.appliedAt).toLocaleDateString("en-NG", { day: "numeric", month: "short" })}</time></li>)}</ul> : <div className="candidate-empty"><p>You have no applications yet.</p><Link className="inline-link" href="/jobs">Find a role</Link></div>}</div>
    </section>

    <section className="candidate-dashboard-grid candidate-dashboard-grid-lower">
      <div className="candidate-panel"><div className="panel-heading"><div><p className="app-eyebrow">Saved for later</p><h2>Saved jobs</h2></div><Heart size={22} aria-hidden="true" /></div>{data.saved.length ? <ul className="candidate-job-list">{data.saved.slice(0, 3).map(item => <li key={item.jobId}><div className="candidate-job-main"><Link href={`/jobs/${item.slug}`}><strong>{item.title}</strong></Link><small>{item.companyName} · {item.workplace}</small></div><CandidateSaveButton jobSlug={item.slug} jobId={item.jobId} title={item.title} initialSaved /></li>)}</ul> : <div className="candidate-empty"><p>Save roles while you compare your options.</p><Link className="inline-link" href="/jobs">Browse jobs</Link></div>}</div>
      <div className="candidate-panel"><div className="panel-heading"><div><p className="app-eyebrow">Stay in the loop</p><h2>Job alerts</h2></div><BellRing size={22} aria-hidden="true" /></div><p className="candidate-stat-copy"><strong>{data.alertsCount}</strong> active {data.alertsCount === 1 ? "alert" : "alerts"} are watching for your next fit.</p><Link className="action-button action-ghost" href="/candidate/job-alerts">Manage alerts</Link></div>
    </section>

    <section className="candidate-intelligence"><div><p className="app-eyebrow">Career Intelligence</p><h2>Make the next application stronger.</h2><p>Use practical tools for your resume, interview preparation, and cover letter before you apply.</p></div><div className="candidate-tool-links"><Link href="/career-tools/resume-scanner"><Sparkles size={18} aria-hidden="true" /><strong>Resume Scanner</strong><ArrowUpRight size={15} aria-hidden="true" /></Link><Link href="/career-tools/interview-prep"><Sparkles size={18} aria-hidden="true" /><strong>Interview Prep</strong><ArrowUpRight size={15} aria-hidden="true" /></Link><Link href="/career-tools/cover-letter"><Sparkles size={18} aria-hidden="true" /><strong>Cover Letter</strong><ArrowUpRight size={15} aria-hidden="true" /></Link></div></section>

    <section className="candidate-panel candidate-notification-summary"><div className="panel-heading"><div><p className="app-eyebrow">Notifications</p><h2>{data.notifications.filter(item => !item.read).length ? `${data.notifications.filter(item => !item.read).length} updates to review` : "You are all caught up"}</h2></div><Link className="text-link" href="/candidate/notifications">Open notifications <ArrowUpRight size={15} aria-hidden="true" /></Link></div>{data.notifications.length ? <ul className="candidate-notification-list">{data.notifications.slice(0, 2).map(item => <li key={item.id}><span className={`notification-dot ${item.read ? "is-read" : ""}`} /><div><strong>{item.title}</strong><p>{item.body}</p></div></li>)}</ul> : <p className="candidate-empty-copy">Application updates and useful prompts will appear here.</p>}</section>
  </CandidateReveal>
}
